steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - hello_world
  - --region=us-east1
  - --source=.
  - --trigger-http
  - --runtime=python312
  - --memory=128MB
  - --timeout=60
  - --min-instances=0
  - --max-instances=1
  - --security-level=secure-always
  - --ingress-settings=all
  - --no-allow-unauthenticated
  - --service-account=hello-world-sa@eloquent-walker-421912.iam.gserviceaccount.com